version: '3'
services:
  tf-serving:
    build: serving
    ports:
    - "2233:2233"
    volumes:
    - "$PWD/models/:/models"
  features:
    build: feature-extractor
    depends_on:
    - tf-serving
    volumes:
    - "$PWD/features:/out"
    - "$PWD/image_spam_data:/data"