version: '3'
services:
  tf-serving:
    build: serving
    ports:
    - "2233:2233"
    volumes:
    - "$PWD/models/:/models"
  features:
    build: feature-extractor
    depends_on:
    - tf-serving
    volumes:
    - "$PWD/features:/out"
    - "$PWD/image_spam_data:/data"
  train-personal:
    build: train
    volumes:
    - "$PWD/features/:/features"
    - "$PWD/train:/train"
    command: "python train.py /features/dredze_ham.json /features/dredze_personal_spam.json dredze_personal"
  train-public:
    build: train
    volumes:
    - "$PWD/features/:/features"
    - "$PWD/train:/train"
    command: "python train.py /features/dredze_ham.json /features/dredze_public_spam.json dredze_public"
  train-princeton:
    build: train
    volumes:
    - "$PWD/features/:/features"
    - "$PWD/train:/train"
    command: "python train.py /features/dredze_ham.json /features/princeton_spam.json princeton"
  train-dredze-combined:
    build: train
    volumes:
    - "$PWD/features/:/features"
    - "$PWD/train:/train"
    command: "python train.py /features/dredze_ham.json /features/dredze_combined_spam.json dredze_combined"
  train-combined:
    build: train
    volumes:
    - "$PWD/features/:/features"
    - "$PWD/train:/train"
    command: "python train.py /features/dredze_ham.json /features/combined_spam.json combined"
  train-email-ds-0_0.0:
    build: train
    volumes:
    - "$PWD/features/:/features"
    - "$PWD/train:/train"
    command: "python train.py /features/image_spam_public.json.gz /features email-ds-0_0.0 0 0.0"
  analyze-email-ds:
    build: train
    volumes:
    - "$PWD/features/:/features"
    - "$PWD/train:/train"
    command: "python analyze.py /features/image_spam_public.json.gz"
